from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib as mpl
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as Canvas


# Ensure using PyQt5 backend
mpl.use('QT5Agg')


# Matplotlib canvas class to create figure
class MplCanvas(Canvas):
    def __init__(self):
        # parent initialisation
        self.fig = Figure()
        self.ax = self.fig.add_subplot(111)
        Canvas.__init__(self, self.fig)
        Canvas.setSizePolicy(self, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        Canvas.updateGeometry(self)


# Matplotlib widget
class MplWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        # parent initialisation
        super().__init__()
        # Create canvas object
        self.canvas = MplCanvas()
        self.vbl = QtWidgets.QVBoxLayout()  # Set box for plotting
        self.vbl.addWidget(self.canvas)
        self.setLayout(self.vbl)


class UI_IS_Model(object):
    def setupUi(self, IS_Model):
        IS_Model.setObjectName("IS_Model")
        IS_Model.resize(640, 530)
        self.centralwidget = QtWidgets.QWidget(IS_Model)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"    background-color: rgb(211, 217, 255)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_3.addWidget(self.lineEdit_7)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton_2.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.step1_mpl1 = MplWidget(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step1_mpl1.sizePolicy().hasHeightForWidth())
        self.step1_mpl1.setSizePolicy(sizePolicy)
        self.step1_mpl1.setObjectName("step1_mpl1")
        self.verticalLayout_2.addWidget(self.step1_mpl1)
        self.step1_mpl2 = MplWidget(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step1_mpl2.sizePolicy().hasHeightForWidth())
        self.step1_mpl2.setSizePolicy(sizePolicy)
        self.step1_mpl2.setObjectName("step1_mpl2")
        self.verticalLayout_2.addWidget(self.step1_mpl2)
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.step2_mpl1 = MplWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step2_mpl1.sizePolicy().hasHeightForWidth())
        self.step2_mpl1.setSizePolicy(sizePolicy)
        self.step2_mpl1.setObjectName("step1_mpl1")
        self.verticalLayout_4.addWidget(self.step2_mpl1)
        self.step2_mpl2 = MplWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step2_mpl2.sizePolicy().hasHeightForWidth())
        self.step2_mpl2.setSizePolicy(sizePolicy)
        self.step2_mpl2.setObjectName("step2_mpl2")
        self.verticalLayout_4.addWidget(self.step2_mpl2)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        IS_Model.setCentralWidget(self.centralwidget)

        self.retranslateUi(IS_Model)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(IS_Model)

    def retranslateUi(self, IS_Model):
        _translate = QtCore.QCoreApplication.translate
        IS_Model.setWindowTitle(_translate("IS_Model", "IS Model"))
        self.label_6.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Plasma parameters</span></p></body></html>"))
        self.label_7.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">Ion temperature</span></p></body></html>"))
        self.lineEdit.setText(_translate("IS_Model", "1000"))
        self.label_8.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">Electron temperature</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("IS_Model", "2000"))
        self.label_9.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">O+ relative fraction</span></p></body></html>"))
        self.lineEdit_3.setText(_translate("IS_Model", "1"))
        self.label_10.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">H+ relative fraction</span></p></body></html>"))
        self.lineEdit_4.setText(_translate("IS_Model", "0"))
        self.label_11.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">He+ relative fraction</span></p></body></html>"))
        self.lineEdit_5.setText(_translate("IS_Model", "0"))
        self.label_14.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Settings</span></p></body></html>"))
        self.label_13.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">Height count</span></p></body></html>"))
        self.lineEdit_7.setText(_translate("IS_Model", "58"))
        self.checkBox_2.setText(_translate("IS_Model", "Add reaults"))
        self.checkBox.setText(_translate("IS_Model", "Noise adding"))
        self.label_12.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">Signal-to-noise ratio</span></p></body></html>"))
        self.lineEdit_6.setText(_translate("IS_Model", "1"))
        self.pushButton.setText(_translate("IS_Model", "Start"))
        self.pushButton_2.setText(_translate("IS_Model", "Clear"))
        self.label_17.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Step 0. Height profiles</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("IS_Model", "Step 0"))
        self.label.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Step 1. IS signal generation on the spectrum</span></p></body></html>"))
        self.label_15.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">0 saved heights</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("IS_Model", "Step 1"))
        self.label_2.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Step 2. Accounting for height extension and noise </span></p></body></html>"))
        self.label_16.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:10pt;\">0 saved heights</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("IS_Model", "Step 2"))
        self.label_3.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Step 3. Trapezoidal summation</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("IS_Model", "Step 3"))
        self.label_4.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Step 4. Acounting for filter impulse response</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("IS_Model", "Step 4"))
        self.label_5.setText(_translate("IS_Model", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Step 5. Results</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("IS_Model", "Step 5"))
        self.checkBox_3.setText(_translate("IS_Model", "All steps"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IS_Model = QtWidgets.QMainWindow()
    ui = UI_IS_Model()
    ui.setupUi(IS_Model)
    IS_Model.show()
    sys.exit(app.exec_())
